{% set git_rev="b43ea6ff45b8b6d9cf29a3b20978417407795cff" %}  {# 3.1.0 #}

package:
  name: conda-verify
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: https://github.com/conda/conda-verify
  # use git rev to point to unique id that doesn't change when github changes git version
  #    This corresponds to the 3.0.0 tag.
  git_rev: {{ git_rev }}

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - jinja2
    - click
    - pyyaml
    - future
    - backports.functools_lru_cache  # [py<33]
    - six
  run_constrained:
    - conda-build  >=3.12.0

build:
  script: pip install . --no-deps

test:
  imports:
    - conda_verify
  commands:
    # return code of version and help is 1 on windows !?
    - conda-verify --version  # [unix]
    - conda-verify --help     # [unix]

about:
  home: https://github.com/conda/conda-verify
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: tool for validating conda recipes and conda packages
  description: |
    conda-verify is a tool for (passively) verifying conda recipes and conda
    packages.

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - mwcraig
    - ocefpaf
    - patricksnape
    - pelson
    - scopatz
    - mandeep
