travis:
  secure:
    BINSTAR_TOKEN: S/SPj+3+JBxZDDSY4Ji7EIE0/5jUP1W2twKx1aO9FbZPIfMqxeyVdV4s6vw+1dbBStLGxXDcb/8/SKTesCcfd3vDjZL7d6s6Ifsp7TXi3FTNuaaOjLOnvi6W7ntHiNPnRHSiZ3LRM2bhhNLtAEeGQHrhEzzbVtqNiJ7vr7XDgBSqh1PDfQb954Nhy8rfWhgTxdEcY2wFVfNT9AUWGHDwHZSOS+jFfWYJDpt4BwISkTjVg6ZagcCqyyLz+t37QLJizM2qsDymWkMpwKSLSIjQKlppqCDmha9YtrAdE7F/oK5wxbFlJfugAXVTLzgPdmN73z+HnO1WnaZr7drhPNQKVURrfvWmiNewiW5t0kix+2OdpyKPGXqRBlvoT5UAqm2OC68kyacnvF6ziAaF+qThc05LcTgxGOQkkMlIhj4SAoeu7TGSa4rfbOI0rPVwTfhvXG3QmnzkY04Sm34zKlgALHWtndu6FCFPjBZkc2VablwSi+hA2Zq2WqOi/edqvS8lfqXhu6+faZiqXwMy+tLdPFjPmJZxoWDtQ6Z9owd7EfFUzBRs2eJY6jCF1dOUq6jEcYe1nf/n84pN8LbkTrgb2hPe7fnfsqXzoTL8eHxbTTgWDQxjn03/2Dt2oM3vaknLT2+yUzRPdFb26SNAv9b7ayrqhjc9GJygeRG3/NXdODw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
