travis:
  secure:
    BINSTAR_TOKEN: FMFBLdK0TZdvDD5m24S/2DUDVPoVxc1cDSk+4BgvsoK9N5Ra13DkHC9ZPBUtq7dDWXt97Y4Pd7WtfPSzeGEca1BHq/uT9I7Sgm+LxXzrI96P85F6AiFEF+B58bFfc9NI4yRp6mrJ30pUibltkfqJQnI383NTCOQfvCxOzMy1PBrFNraMgI1Zs3IMAVVu0bBzy/EWK9lhgkJOOPx1djwTQRl7i03whgZeOCpBy5UWDE1W7R+flEbYRYz35KVb05tB6LmTN8a5k8TjFD7NGkPEGgSrEUFYYO+4oQk7io4WfC9pogtZNYxvo+BWcbQqV2/9Yxw25/nEeNgTUBjP5mCld5Xea2z3tqaBD18N4p0cYM4ItgBUHDjcpMkBr9II7E/EkQ0yKtDTCHJZYACkfIr20mCentr7GKc8Zyl2dc+mGoQ2WQzKyiOCWCpvwrIdjXid1BzZwtKpBv3wOdHUaS24hJMWlLhRBcqCm0b4CDXNMI9MnP2wPzqvKjwekPGGU2Mv+Dxxgf8cl7ZrJ+Tv7cUAvzFpkVXOwYyDrJ7fAC8ShhuoaArdf6VjZBavxFCh/kWNR91HZ9RYtps1RJDIldKgW3W3nvEIzsEU8TFEmK1VUWJgx/O0SYN4JQBSHDl4DQklgHKlSV9hiPWUEP1Pch35E+9rSUJueLVdbTZeRE4gBdM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
